version: '3'

services:

  cdt-be: # serves on 8080
    image: eightwelve/cdt-be:master-20190621204218
    ports:
      - "6014:8080"
    expose:
      - "8080" # let other containers access to this service on 8080
    restart: always

  cdt-web:
    image: eightwelve/cdt-web:master-20190622070949
    ports:
      - "6015:5000"
    expose:
      - "5000"
    depends_on:
      - cdt-be
    environment:
      - REACT_APP_API_ENDPOINT=http://localhost:6014
    restart: always
